

services:
  postgres:
    image: postgres:17
    container_name: ops-flow-postgres
    environment:
      POSTGRES_USER: opsflow
      POSTGRES_PASSWORD: opsflow
      POSTGRES_DB: opsflow
    
    ports:
      - "5432:5432"
    
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: