# Generated by Django 6.1.1 on 2026-10-03 14:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationmember',
            name='unique_organization_member',
        ),
        migrations.RenameField(
            model_name='organizationmember',
            old_name='organisation',
            new_name='organization',
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_member'),
        ),
    ]
